let flights = [{
        id: 1,
        location: "Kenya",
        title: "flight to Kenya",
        time: "1pm",
        price: "26000",
        date: "26/11/2022",
    },
    {
        id: 2,
        location: "Uganda",
        title: "flight to Uganda",
        time: "12pm",
        price: "14000",
        date: "22/11/2022",
    },
    {
        id: 3,
        location: "australia",
        title: "flight to australia",
        time: "3am",
        price: "56000",
        date: "23/11/2020",
    },
    {
        id: 4,
        location: "Somalia",
        title: "flight to Somalia",
        time: "4pm",
        price: "40000",
        date: "07/11/2022",
    },
    {
        id: 5,
        location: "Nigeria",
        title: "flight to Nigeria",
        time: "6pm",
        price: "600000",
        date: "28/11/2022",
    },
    {
        id: 6,
        location: "Egypt",
        title: "flight to Egypt",
        time: "5am",
        price: "450000",
        data: "01/12/2022",
    },
];

module.exports = flights;